name: C++ CI with Google Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install build tools and dependencies
      - name: Install build tools and Google Test dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      # Step 3: Configure Google Test
      - name: Setup Google Test
        run: |
          git clone https://github.com/google/googletest.git
          mkdir -p googletest/build
          cd googletest/build
          cmake ..            # Corrected: Point to the source directory for configuration
          make
          sudo make install

      # Step 4: Build the project
      - name: Build C++ Program and Tests
        run: |
          mkdir -p build
          cd build
          cmake ..            # Corrected: Use the correct directory for your CMakeLists.txt
          make

      # Step 5: Run tests
      - name: Run Google Tests
        run: ./build/test
